{% set name = "ttyd" %}
{% set version = "1.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tsl0922/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1116419527edfe73717b71407fb6e06f46098fc8a8e6b0bb778c4c75dc9f64b9

build:
  number: 2
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make   # [unix]
    - cmake
    - pkg-config
    - vim
  host:
    - json-c
    - libwebsockets
    - openssl
    - libuv
  run:
    - json-c

test:
  commands:
    - ttyd

about:
  home: http://github.com/tsl0922/ttyd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Share your terminal over the web

  dev_url: https://github.com/tsl0922/ttyd

extra:
  recipe-maintainers:
    - sodre
