travis:
  secure:
    BINSTAR_TOKEN: Ew2o9Uvw/EAJpDm40MqvZtaEUgqyoXV3H33gRZ+KKvHnus4K9Z6SQA2ygXhi8FgMvZwhT8o70X7sq6FYGn4TW14inZ+/1+SojOjGMA7b90en5plztvsN5fSO+qTa5MQZqXkKCWUZopuAa1pkMsZs12P5nSVwXnc9cOrD8ombPvt4kvLEBu+6v63SlkQKybJJM0VsrxZE3cYaUj1tC9/LFODZ2v5BxM/wQexttbQtOwKNEpjuAoDR2qsnDMcDetBYcyDmR9Lr6dPWO+JA89OHAP3/v+FPgkltA70KZmKry9FW7UyyixqftuBxJ84Y/uIj1NECgGRIhFN/jpjh7ZhRTik2ba+chfvFeWnbA3OqvIsR6WwCPoZpQcF8+k4Fg1TfKvaxqlPsO55CVFmvn54OBHwjy60Rh13lTzwHETqxPC7joUnxBjhkwe7ekTlncEjbLWyh3WfTS+xRiRhYogrlFcbiNCUD+v7d/6DASySMVoPlDodcUXvRntVzRaKusJtT4yAYggVo5/3VZoNQUG7X3MNQG9f2n0Sc1Ny4qVAnwLlsVzCgckeOvMYUQcztMg60f7/F227dQp4m9YZXaVvGvcM37Zb+HrX5E0sMOfhANnOQ/rj2YL44avhNxOECbdB2S19xBVxMYvD5gBQ5Y2zTg2PpzFtzctx/tPmjAhOyWrY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
